### PR TITLE
Improved sphere creation

### PR DESCRIPTION
**Pull request by NiLSPACE**
A sphere 90x90x90 now takes only 1.6 seconds on an I7-4700MQ

### CODE REVIEW

**Comment by NiLSPACE** [comment]
I'm planning on doing the same thing for cylinders. Should I do that in the same PR, or do it in a different one?

**Comment by madmaxoft** [comment]
... instead of the previous ??? seconds?

**Comment by NiLSPACE** [comment]
Oh, right, sorry. 1.6 seconds vs 53.967 seconds.

**Comment by madmaxoft** [comment]
That is some serious performance improvement, congratulations!
It's up to you if you want to do the cylinder here as well.

**Comment by NiLSPACE** [comment]
Thanks, I had the idea in my head for quite a while, but I never expected it to be this fast.

I'll do the cylinder's here as well.

**Comment by NiLSPACE** [comment]
Done

**Comment by madmaxoft** [comment]
Looks good

**Pull request merged**
