### PR TITLE
Rewritten API to have a single function called CallHook to call a hook, ...

### PR DESCRIPTION
**Pull request by NiLSPACE**
...and a function to add one

### CODE REVIEW

**Comment by NiLSPACE** [comment]
I also created some documentation (manualy.. ugh): http://worldedit.nilspace.nl/apidocs/

**Comment by madmaxoft** [comment]
How about providing a "compatibility bridge" between the new API and the old API, so that plugins using the old API can be updated gradually.

**Comment by NiLSPACE** [comment]
I kinda already have that, except of course that the parameters [are different](https://github.com/mc-server/WorldEdit/pull/72/files#diff-be28aa4c2520886913872deb89e08f1fR62)

**Comment by NiLSPACE** [comment]
I don't think it's worth to completely make a bridge, since the only plugin we know of that uses the WorldEdit hook is Gallery, and my [WE-SpawnProtect](https://github.com/NiLSPACE/WE-SpawnProtect)

**Comment by NiLSPACE** [comment]
Or do you really want the bridge to be there? I would have to change some things in the CallHook and AddHook function so that it also accepts functions from WorldEdit.

**Comment by madmaxoft** [comment]
I guess it's okay this way.

**Pull request merged**
