### PR TITLE
Added cBlockDstXYZ classes

### PR DESCRIPTION
**Pull request by NiLSPACE**
Implements #49

### CODE REVIEW

**Comment by madmaxoft** [comment]
The naming is somewhat weird; combined with a lack of documentation, that is a maintenance problem just waiting to happen.

**Comment by NiLSPACE** [comment]
I named them `cBlockDstXYZ` instead of `cBlockTypeSourceXYZ` because they aren't used to interact with the source (or original) blocks, but to change the final (or destination) block. How would you name them otherwise?

**Comment by madmaxoft** [comment]
`cBlockTypeSource` - source of blocktypes. Usually, you don't `Get` from a `Dst`. You `Get` from a `Src` and `Put` into a `Dst`

**Comment by NiLSPACE** [comment]
Okay, no that I read that it makes sense, but how would I name [cBlockSrc](https://github.com/mc-server/WorldEdit/blob/BlockDst/Classes/BlockSrc.lua) then?

**Comment by NiLSPACE** [comment]
Though I'm not sure if the word `type` should be in the name :|

**Comment by madmaxoft** [comment]
I have no idea what that class does, so I can't be of help here.

**Comment by NiLSPACE** [comment]
I added some documentation to it. (I'm also adding documentation to the other files)

The class basicly represents all blocks that can be replaced.

**Comment by NiLSPACE** [comment]
Another option would be to name it `cMask`?

**Comment by NiLSPACE** [comment]
I renamed cBlockSrc to cMask

**Comment by NiLSPACE** [comment]
Is it alright like this, or is some documentation unclear or lacking?

**Comment by NiLSPACE** [comment]
I'm gonna merge this in about an hour.

**Pull request merged**
